<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <?php
    echo $this->tag->getTitle();
    ?>
    <style>
        .modal-header, h4, .close {
            background-color: #5cb85c;
            color:white !important;
            text-align: center;
            font-size: 30px;
        }
        .modal-footer {
            background-color: #f9f9f9;
        }
    </style>
</head>
<body>
<?php
if($this->session->get("user")!=null){
    echo "
    <script>
    $(document).ready(function(){
        $(\"#myModal\").modal('static');
    });
</script>
    ";
}else{
    echo "<script>
    $(document).ready(function(){
        $(\"#myModal\").modal('hide');
    })
</script>
    ";
}
?>
<div class="container" id="modalwindow">
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header" style="padding:35px 50px;">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4><span class="glyphicon glyphicon-lock"></span> Login</h4>
                </div>
                <div class="modal-body" style="padding:40px 50px;">
                    <form role="form" action="../auth/check" method="post">
                        <div class="form-group">
                            <label for="username"><span class="glyphicon glyphicon-user"></span> Пользователь:</label>
                            <input type="text" class="form-control" name="Login" id="username" placeholder="Введите имя пользователя">
                        </div>
                        <div class="form-group">
                            <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Пароль:</label>
                            <input type="password" class="form-control" name="Password" id="psw" placeholder="Введите пароль">
                        </div>
                        <button type="submit" class="btn btn-success btn-block"><span class="glyphicon glyphicon-off"></span> Авторизоваться</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Отмена</button>
                </div>
            </div>

        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        $("#myModal").modal('show');
    });
</script>
<div class="row">
    <div class="col-sm-12">
        <h1 class="text-center">ДЕКАНАТ</h1>
    </div>
</div>
<nav role="navigation" class="navbar navbar-default navbar-static-top">
    <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li class="active"><a href="index">Главная</a></li>
            <li><a href="reports/shedule">Расписание</a></li>
            <li><a href="reports/list_of_group">Список группы</a></li>
            <li><a href="excel">Изменить расписание</a></li>
            <li><a href="#">Отчеты</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#" class="nav navbar-nav">Выйти</a></li>
        </ul>
    </div>
</nav>
</body>
</html>
