
<?php echo $this->tag->form("reports/shedule");?>

    <?php echo $this->tag->submitButton("Посмотреть расписание") ?>
</p>
<?php echo $this->tag->form("reports/list_of_group");?>
<p>
    <?php echo $this->tag->submitButton("Посмотреть список группы") ?>
</p>
<?php echo $this->tag->form("reports/attend_student");?>
<p>
    <?php echo $this->tag->submitButton("Посмотреть информацию о посещаемости студента") ?>
</p>
<?php echo $this->tag->form("reports/attend");?>
<p>
    <?php echo $this->tag->submitButton('Посмотреть посещаемость группы') ?>
</p>