<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="img/favicon.ico">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <?php
    echo $this->tag->getTitle();
    $this->assets->outputCss();
    $this->assets->outputJs();
    ?>
</head>
<body>
<div class="row">
    <div class="col-sm-12">
        <h1 class="text-center">ДЕКАНАТ</h1>
    </div>
</div>
<nav role="navigation" class="navbar navbar-default navbar-static-top">
    <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li><a href="../index">Главная</a></li>
            <li><a href="shedule">Расписание</a></li>
            <li class="active"><a href="list_of_group">Список группы</a></li>
            <li><a href="../excel">Изменить расписание</a></li>
            <li><a href="#">Отчеты</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Выйти</a></li>
        </ul>
    </div>
</nav>
<div class="col-sm-4">
    <form name="group" class="form-group" action="#" method="post">
        <select id="group" class="form-control">
            <option class="hidden">Выберите группу...</option>
            <?php
            foreach ($groups as $group) {
                echo "<option value='" . $group->getIDGroup() . "'>" . $group->getNameGroup() . "</option> \n";
            }
            ?>
        </select>
        <br>
        <input class="btn btn-default" type="button" value="Просмотреть" id="show">
    </form>
</div>
<div class="col-sm-8"></div>
<br>
<br>

<div class="col-sm-1"></div>
<div class="col-sm-10" id="table"></div>
<script>
    $(document).ready(function () {
        $("#show").click(function () {
            var group = $("#group").val();
            $.ajax({
                type: 'POST',
                url: '../reports/list_of_group',
                data: 'group=' + group,
                dataType: 'json',
                success: function (responseData) {
                    var html = "<table class='table'>" +
                        "<thead>" +
                        "<tr>" +
                        "<th>ФИО</th>" +
                        "<th>Телефон</th>" +
                        "<th>E-mail</th>" +
                        "</tr>" +
                        "</thead>" +
                        "<tbody>";
                    $.each(responseData, function () {
                        var str=this.Name.toString().replace("_"," ");

                        html += "<tr>" +
                            "<td>" + str + "</td>" +
                            "<td>&mdash;</td>" +
                            "<td>&mdash;</td>" +
                            "</tr>";
                    });
                    html += "</tbody>" +
                        "</table>";
                    document.getElementById('table').innerHTML = html;
                }
            })
        });
    });
</script>
</body>
</html>