<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="img/favicon.ico">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <?php
    echo $this->tag->getTitle();
    $this->assets->outputCss();
    $this->assets->outputJs();
    ?>
</head>
<body>
<div class="row">
    <div class="col-sm-12">
        <h1 class="text-center">ДЕКАНАТ</h1>
    </div>
</div>
<nav role="navigation" class="navbar navbar-default navbar-static-top">
    <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li><a href="../index">Главная</a></li>
            <li class="active"><a href="shedule">Расписание</a></li>
            <li><a href="list_of_group">Список группы</a></li>
            <li><a href="../excel">Изменить расписание</a></li>
            <li><a href="#">Отчеты</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Выйти</a></li>
        </ul>
    </div>
</nav>
<div>
    <!-- Навигация -->
    <ul class="nav nav-tabs" role="tablist">
        <li class="active"><a href="#all" aria-controls="all" role="tab" data-toggle="tab">Общее</a></li>
        <li><a href="#forgroup" aria-controls="forgroup" role="tab" data-toggle="tab">По дням</a></li>
    </ul>
    <!-- Содержимое вкладок -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="all">
            <!-выводим общее расписание для всех групп-->
        </div>
        <div role="tabpanel" class="tab-pane" id="forgroup">
            <div class="col-sm-4">
                <form name="group" class="form-group" action="#" method="post">
                    <select id="group" class="form-control">
                        <option class="hidden">Выберите группу...</option>
                        <?php
                        foreach ($groups as $group) {
                            echo "<option value='" . $group->getIDGroup() . "'>" . $group->getNameGroup() . "</option> \n";
                        }
                        ?>
                    </select>
                    <br>
                    <input class="btn btn-default" type="button" value="Просмотреть" id="show">
                </form>
            </div>
            <div class="col-sm-1"></div>
            <div class="col-sm-10" id="table">
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#show").click(function () {
            var group = $("#group").val();
            $.ajax({
                type: 'POST',
                url: '../reports/shedule',
                data: 'group=' + group,
                dataType: 'json',
                success: function (responseData) {
                    var html = "<table class='table'>" +
                        "<thead>" +
                        "<tr>" +
                        "<th>Дата</th>" +
                        "<th>Номер</th>" +
                        "<th>Предмет</th>" +
                        "</tr>" +
                        "</thead>" +
                        "<tbody>";
                    $.each(responseData, function () {
                        html += "<tr>" +
                            "<td>" + this.Weekday + "</td>" +
                            "<td>" + this.Number + "</td>" +
                            "<td>" + this.Name + "</td>" +
                            "</tr>";
                    });
                    html += "</tbody>" +
                        "</table>";
                    document.getElementById('table').innerHTML = html;
                }
            })
        });
    });
</script>
</body>
</html>