<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="img/favicon.ico">
    <?php
    echo $this->tag->getTitle();
    $this->assets->outputCss();
    ?>
</head>
<body>
<div class="row">
    <div class="col-sm-12">
        <h1 class="text-center">ДЕКАНАТ</h1>
    </div>
</div>
<nav role="navigation" class="navbar navbar-default navbar-static-top">
    <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li><a href="../index">Главная</a></li>
            <li><a href="../reports/shedule">Расписание</a></li>
            <li><a href="../reports/list_of_group">Список группы</a></li>
            <li class="active"><a href="excel">Изменить расписание</a></li>
            <li><a href="#">Отчеты</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Выйти</a></li>
        </ul>
    </div>
</nav>
<form class="form-group" enctype="multipart/form-data" action="excel/check" method="post">
    <label class="btn btn-default btn-file">
        Выберите файл <input name="userfile" type="file" style="display: none;" >
    </label>
    <input class="btn btn-default" type="submit" value="Редактировать" id="change">
</form>
<script>
    $(document).ready(function () {
        $("#change").click(function () {
            var formData= new FormData($('form')[0]);
            $.ajax({
                type: 'POST',
                url: '../excel/check',
                contentType: false,
                processData: false,
                data: formData,
                success: function () {
                    alert("kamilah");
                }
            })
        });
    });
</script>
</body>
</html>

