<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="favicon.ico">
    <?php echo $this->tag->getTitle()?>
</head>
<body>
<h2>Авторизуйтесь, используя эту форму</h2>

<?php echo $this->tag->form("auth/check"); ?>

<p>
    <label for="Login">Login</label>
    <?php echo $this->tag->textField("Login") ?>
</p>

<p>
    <label for="Password">Пароль</label>
    <?php echo $this->tag->passwordField("Password") ?>
</p>

<p>
    <?php echo $this->tag->submitButton("Авторизоваться") ?>
</p>
    <?php echo $this->tag->endForm()?>
</body>
</html>
